# Site settings
title: Iraj Ahangari
description: >-  
  Techni-philosophy
baseurl: ""           # leave empty for username.github.io
url: "https://techphilo.github.io"

#theme: minimal-mistakes-jekyll

# Use Hydejack via remote_theme
remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  
# Author settings
author:
  name: "Iraj Ahangari"
  avatar: "/assets/images/avatar.jpg"   # optional

# Social links (will show in header/footer automatically)
header-links:
  - name: GitHub
    url: https://github.com/<your-username>
  - name: Twitter
    url: https://twitter.com/<your-handle>
  - name: LinkedIn
    url: https://linkedin.com/in/<your-id>

plugins:
  - jekyll-feed        # RSS feed
  - jekyll-seo-tag     # SEO meta tags
